### PR TITLE
Programmatic api

### PR DESCRIPTION
**Pull request by perrin4869**
Stops using `ttf2eot` and `ttf2svg` as commands, opting for their programmatic API, and adds them as `npm` dependencies.

Fixes:

* https://github.com/agentk/fontfacegen/issues/33, as `ttf2svg` works on Linux and Mac (unless we want to support windows too)
* https://github.com/agentk/fontfacegen/issues/32, as no more external dependencies are necessary (except for `fontforge`, but nothing can be done about it as far as I can tell).
* https://github.com/agentk/fontfacegen/issues/23, svg is working properly now

### CODE REVIEW

**Comment by perrin4869** [comment]
@agentk @sgen @julianxhokaxhiu appreciate if you can take a look and merge if it's ok :)
Tested in Slackware, Arch and OS X, working well for me!

**Comment by julianxhokaxhiu** [comment]
Tested and working perfectly! Thank you :)

**Comment by perrin4869** [comment]
Awesome! @agentk can you release 0.2.1 as a bug fix patch? svg generation is working now

**Comment by julianxhokaxhiu** [comment]
@perrin4869 done :)

**Comment by perrin4869** [comment]
Thanks man!

**Pull request merged**
